### ISSUE TITLE
Coveralls fails!

### ISSUE THREAD

**Issue by meetrp** [meetrp/sniffer.py#39]
**Describe the bug**
From the Travis CI log, it appears like the coveralls is failing.

**Screenshots**
```
$> coveralls
/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/coveralls", line 7, in <module>
    from coveralls.cli import main
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/coveralls/__init__.py", line 2, in <module>
    from .api import Coveralls
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/coveralls/api.py", line 9, in <module>
    import requests
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Additional context**
Check this: [Travis CI Build #24](https://travis-ci.org/meetrp/psa/builds/442382955)

**Comment by meetrp** [comment]
This is not an issue. This was fixed by #49 (I think!)
